import { useCallback, useMemo } from 'react';
import { useDataContext } from '../data/DataContext';
import useStoredParams from '../page/useStoredParams';

const ExportWidget: React.FC = () => {
  const { value: targetLanguage } = useStoredParams('targetLanguage', 'eng');
  const { monthsData } = useDataContext();

  const monthsWide = monthsData.map(
    (month, index) => `<month type="${index + 1}">${month.wide?.translated ?? ''}</month>`,
  );
  const monthsAbbreviated = monthsData.map(
    (month, index) => `<month type="${index + 1}">${month.abbreviated?.translated ?? ''}</month>`,
  );
  const monthsNarrow = monthsData.map(
    (month, index) => `<month type="${index + 1}">${month.narrow?.translated ?? ''}</month>`,
  );

  const fullXML = useMemo(() => {
    return `<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE ldml SYSTEM "../../common/dtd/ldml.dtd">
<!-- Generated by Mokblok Tools on ${new Date().toISOString()} -->
<ldml>
<identity>
  <version number="$Revision$"/>
  <language type="${targetLanguage}"/>
</identity>
<calendars>
  <calendar type="gregorian">
    <months>
      <monthContext type="format">
        <monthWidth type="wide">
${monthsWide.map((line) => ' '.repeat(10) + line).join('\n')}
        </monthWidth>
        <monthWidth type="abbreviated">
${monthsAbbreviated.map((line) => ' '.repeat(10) + line).join('\n')}
        </monthWidth>
        <monthWidth type="narrow">
${monthsNarrow.map((line) => ' '.repeat(10) + line).join('\n')}
        </monthWidth>
      </monthContext>
    </months>
  </calendar>
</calendars>
</ldml>`;
  }, [monthsWide, monthsAbbreviated, monthsNarrow, targetLanguage]);

  const handleDownload = useCallback(() => {
    const blob = new Blob([fullXML], { type: 'application/xml' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = `${targetLanguage}.xml`;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    URL.revokeObjectURL(url);
  }, [fullXML, targetLanguage]);

  return (
    <div style={{ display: 'flex', flexDirection: 'column', gap: '1em' }}>
      <textarea style={{ width: '40em', height: '30em' }} value={fullXML} readOnly />
      <button onClick={handleDownload}>Download</button>
    </div>
  );
};

export default ExportWidget;
