import { useMemo } from 'react';
import { useTranslation } from 'react-i18next';

import { useSettings } from '@settings/Settings';

import ExportDownloadXMLButton from './ExportDownloadXMLButton';
import useXMLFormattedData from './useXMLFormattedData';

const ExportXMLData: React.FC = () => {
  const { t } = useTranslation();
  const { targetLanguageBCP, coverageLevel } = useSettings();
  const ldml = useXMLFormattedData();

  const fullXML = useMemo(() => {
    return `<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE ldml SYSTEM "../../common/dtd/ldml.dtd">
<!-- Generated by Mokblok Tools on ${new Date().toISOString()} -->
<ldml>
  <identity>
    <version number="$Revision$"/>
    <language type="${targetLanguageBCP}"/>
  </identity>
${ldml}
</ldml>`;
  }, [ldml, targetLanguageBCP]);

  return (
    <>
      <div>
        <strong>{t('export.fullXmlTitle')}</strong>
        <ExportDownloadXMLButton filename={coverageLevel} xmlContent={fullXML} />
      </div>
      <span>
        {t('export.cldrUploadPrefix')}{' '}
        <a href={t('export.cldrUploadUrl')}>{t('export.cldrUploadUrl')}</a>
      </span>
      <textarea style={{ width: '40em', height: '30em' }} value={fullXML} readOnly />
    </>
  );
};

export default ExportXMLData;
