import { useMemo } from 'react';

import { useSourceDataContext } from '@data/source/SourceDataProvider';
import { useTargetDataContext } from '@data/target/TargetDataProvider';

import { getLanguageBCP } from '@settings/LanguageCodes';
import { useURLParams } from '@settings/URLParams';

import useInterfaceTranslation from '@shared/useInterfaceTranslation';

import ExportDownloadXMLButton from './ExportDownloadXMLButton';

// In order to function in XML correctly these need to be escaped.
const punctuationTransforms: Record<string, string> = {
  '-': '\\-',
  ':': '\\:',
  '[': '\\[',
  ']': '\\]',
  '{': '\\{',
  '}': '\\}',
  '&': '\\&amp;',
  '"': '&quot;',
};
const standardPunctuation = ['-‑,;:!?.…\'‘’"“”()[]§@/&#%′″'];

const ExportCoreData: React.FC = () => {
  const { uitext } = useInterfaceTranslation();
  const { targetLanguage } = useURLParams();
  const targetLanguageBCP = getLanguageBCP(targetLanguage);
  const { findDataEntry } = useSourceDataContext();
  const { alphabet, getTranslation } = useTargetDataContext();
  const { charactersNumber, charactersAuxiliary, charactersBase, charactersPunctuation } =
    alphabet || {};
  const endonym = getTranslation(
    findDataEntry({ field: 'LocaleDisplayNames', instance: targetLanguageBCP }),
    false /* don't fall back to English */,
  );

  const formattedPunctuations = useMemo(() => {
    // Sort by "standardPunctuation" order
    const puncs = charactersPunctuation
      ?.slice()
      .sort((a, b) => standardPunctuation.indexOf(a) - standardPunctuation.indexOf(b));
    return puncs?.map((char) => punctuationTransforms[char] || char).join(' ');
  }, [charactersPunctuation]);

  const fullXML = useMemo(() => {
    return (
      `<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE ldml SYSTEM "../../common/dtd/ldml.dtd">
<!-- Generated by Mokblok Tools on ${new Date().toISOString()} -->
<ldml>
  <identity>
    <version number="$Revision$"/>
    <language type="${targetLanguageBCP}"/>
  </identity>
` +
      (endonym
        ? `  <localeDisplayNames>
    <languages>
      <language type="${targetLanguageBCP}">${endonym}</language>
    </languages>
  </localeDisplayNames>
`
        : '') +
      `
  <characters>
    <exemplarCharacters>[${charactersBase?.join(' ')}]</exemplarCharacters>
    <exemplarCharacters type="auxiliary">[${charactersAuxiliary?.join(' ')}]</exemplarCharacters>
    <exemplarCharacters type="numbers">[${charactersNumber?.join(' ')}]</exemplarCharacters>
    <exemplarCharacters type="punctuation">[${formattedPunctuations}]</exemplarCharacters>
  </characters> 
</ldml>

</dates>
</ldml>`.replaceAll(/^\s*\n/gm, '')
    ); // Remove empty lines
  }, [
    charactersAuxiliary,
    charactersBase,
    charactersNumber,
    formattedPunctuations,
    endonym,
    targetLanguageBCP,
  ]);

  return (
    <>
      <h3>
        {uitext('export.coreLocaleDataTitle')}
        <ExportDownloadXMLButton filename="core" xmlContent={fullXML} />
      </h3>
      <span>
        {uitext('export.coreLocaleInstructions')} <code>{targetLanguage}.xml</code>
      </span>
      <textarea style={{ width: '40em', height: '10em' }} value={fullXML} readOnly />
    </>
  );
};

export default ExportCoreData;
