import { useMemo } from 'react';

import { useSettings } from '@settings/Settings';

import ExportDownloadXMLButton from './ExportDownloadXMLButton';
import useXMLFormattedData from './useXMLFormattedData';

const ExportDatePatterns: React.FC = () => {
  const { targetLanguage } = useSettings();
  const { monthsXML, daysOfWeekXML, dateFieldsXML } = useXMLFormattedData();

  const fullXML = useMemo(() => {
    return `<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE ldml SYSTEM "../../common/dtd/ldml.dtd">
<!-- Generated by Mokblok Tools on ${new Date().toISOString()} -->
<ldml>
<identity>
  <version number="$Revision$"/>
  <language type="${targetLanguage}"/>
</identity>
<dates>
  <calendars>
    <calendar type="gregorian">
${monthsXML}
${daysOfWeekXML}
${dateFieldsXML}
    </calendar>
  </calendars>
</dates>
</ldml>`.replaceAll(/^\s*\n/gm, ''); // Remove empty lines
  }, [monthsXML, daysOfWeekXML, dateFieldsXML, targetLanguage]);

  return (
    <>
      <div>
        <strong>Date patterns</strong>
        <ExportDownloadXMLButton filename="datepatterns" xmlContent={fullXML} />
      </div>
      <span>
        Contribute this data to CLDR in the Survey Tool bulk upload tool{' '}
        <a href="https://st.unicode.org/cldr-apps/v#upload///">
          https://st.unicode.org/cldr-apps/v#upload///
        </a>
      </span>
      <textarea style={{ width: '40em', height: '30em' }} value={fullXML} readOnly />
    </>
  );
};

export default ExportDatePatterns;
