import { useCallback, useMemo } from 'react';

import { useSettings } from '@settings/Settings';

import useXMLFormattedData from './useXMLFormattedData';

const ExportWidget: React.FC = () => {
  const { targetLanguage } = useSettings();
  const { monthsXML, daysOfWeekXML, dateFieldsXML } = useXMLFormattedData();

  const fullXML = useMemo(() => {
    return `<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE ldml SYSTEM "../../common/dtd/ldml.dtd">
<!-- Generated by Mokblok Tools on ${new Date().toISOString()} -->
<ldml>
<identity>
  <version number="$Revision$"/>
  <language type="${targetLanguage}"/>
</identity>
<dates>
  <calendars>
    <calendar type="gregorian">
${monthsXML}
${daysOfWeekXML}
${dateFieldsXML}
    </calendar>
  </calendars>
</dates>
</ldml>`.replaceAll(/^\s*\n/gm, ''); // Remove empty lines
  }, [monthsXML, daysOfWeekXML, dateFieldsXML, targetLanguage]);

  const handleDownload = useCallback(() => {
    const blob = new Blob([fullXML], { type: 'application/xml' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = `${targetLanguage}.xml`;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    URL.revokeObjectURL(url);
  }, [fullXML, targetLanguage]);

  return (
    <div style={{ display: 'flex', flexDirection: 'column', gap: '1em' }}>
      <textarea style={{ width: '40em', height: '30em' }} value={fullXML} readOnly />
      <button onClick={handleDownload}>Download</button>
    </div>
  );
};

export default ExportWidget;
