import { useMemo } from 'react';

import { getCoverageLevelLabel } from '@data/CoverageLevel';

import { getLanguageBCP } from '@settings/LanguageCodes';
import { useURLParams } from '@settings/URLParams';

import useInterfaceTranslation from '@shared/useInterfaceTranslation';

import ExportDownloadXMLButton from './ExportDownloadXMLButton';
import useXMLFormattedData from './useXMLFormattedData';

const ExportXMLData: React.FC = () => {
  const { uitext } = useInterfaceTranslation();
  const { targetLanguage, coverageLevel } = useURLParams();
  const targetLanguageBCP = getLanguageBCP(targetLanguage);
  const ldml = useXMLFormattedData();

  const fullXML = useMemo(() => {
    return `<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE ldml SYSTEM "../../common/dtd/ldml.dtd">
<!-- Generated by Mokblok Tools on ${new Date().toISOString()} -->
<ldml>
  <identity>
    <version number="$Revision$"/>
    <language type="${targetLanguageBCP}"/>
  </identity>
${ldml}
</ldml>`;
  }, [ldml, targetLanguageBCP]);

  return (
    <>
      <h3>
        {uitext('export.fullXmlTitle')}
        <ExportDownloadXMLButton
          filename={getCoverageLevelLabel(coverageLevel)}
          xmlContent={fullXML}
        />
      </h3>
      <span>
        {uitext('export.cldrUploadPrefix')}{' '}
        <a href={uitext('export.cldrUploadUrl')}>{uitext('export.cldrUploadUrl')}</a>
      </span>
      <textarea style={{ width: '40em', height: '30em' }} value={fullXML} readOnly />
    </>
  );
};

export default ExportXMLData;
