import { useMemo } from 'react';

import { useDataContext } from '@data/DataContext';

import { useSettings } from '@settings/Settings';

import ExportDownloadXMLButton from './ExportDownloadXMLButton';

// In order to function in XML correctly these need to be escaped.
const punctuationTransforms: Record<string, string> = {
  '-': '\\-',
  ':': '\\:',
  '[': '\\[',
  ']': '\\]',
  '{': '\\{',
  '}': '\\}',
  '&': '\\&amp;',
  '"': '&quot;',
};
const standardPunctuation = ['-‑,;:!?.…\'‘’"“”()[]§@/&#%′″'];

const ExportCoreData: React.FC = () => {
  const { targetLanguage } = useSettings();

  const { charactersNumber, charactersAuxiliary, charactersBase, charactersPunctuation } =
    useDataContext().alphabetData || {};

  const formattedPunctuations = useMemo(() => {
    // Sort by "standardPunctuation" order
    const puncs = charactersPunctuation
      ?.slice()
      .sort((a, b) => standardPunctuation.indexOf(a) - standardPunctuation.indexOf(b));
    return puncs?.map((char) => punctuationTransforms[char] || char).join(' ');
  }, [charactersPunctuation]);

  const fullXML = useMemo(() => {
    return `<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE ldml SYSTEM "../../common/dtd/ldml.dtd">
<!-- Generated by Mokblok Tools on ${new Date().toISOString()} -->
<ldml>
  <identity>
    <version number="$Revision$"/>
    <language type="${targetLanguage}"/>
  </identity>
  <localeDisplayNames>
    <languages>
      <language type="${targetLanguage}">!!!!!</language>
    </languages>
  </localeDisplayNames>
  <characters>
    <exemplarCharacters>[${charactersBase?.join(' ')}]</exemplarCharacters>
    <exemplarCharacters type="auxiliary">[${charactersAuxiliary?.join(' ')}]</exemplarCharacters>
    <exemplarCharacters type="numbers">[${charactersNumber?.join(' ')}]</exemplarCharacters>
    <exemplarCharacters type="punctuation">[${formattedPunctuations}]</exemplarCharacters>
  </characters> 
</ldml>

</dates>
</ldml>`.replaceAll(/^\s*\n/gm, ''); // Remove empty lines
  }, [
    charactersAuxiliary,
    charactersBase,
    charactersNumber,
    formattedPunctuations,
    targetLanguage,
  ]);

  return (
    <>
      <div>
        <strong>Core Locale Data </strong>
        <ExportDownloadXMLButton filename="core" xmlContent={fullXML} />
      </div>
      <span>
        In order to add the locale to the survey tool, submit this to a new datafile{' '}
        <code>{targetLanguage}.xml</code>
      </span>
      <textarea style={{ width: '40em', height: '10em' }} value={fullXML} readOnly />
    </>
  );
};

export default ExportCoreData;
